-- ============================================================
-- LOKITA — Section 3 (Orders): real transaction lifecycle + realtime.
-- Apply after 0001–0003. Safe to re-run.
--
-- Lifecycle (maps to the requested paid→…→completed flow):
--   paid         buyer has committed/paid — awaiting seller drop-off
--   dropped_off  seller handed off / dropped at Security Post — awaiting pickup
--   completed    buyer confirmed pickup — trade done, reviews unlocked
--   cancelled    either party cancelled
-- payment_status (cod/qris) tracks money separately.
-- ============================================================

-- widen the status CHECK to the lifecycle values
alter table public.transactions drop constraint if exists transactions_status_check;
alter table public.transactions
  add constraint transactions_status_check
  check (status in ('paid', 'dropped_off', 'completed', 'cancelled'));
alter table public.transactions alter column status set default 'paid';

-- lifecycle timestamps (deadlines generated by the app on each transition)
alter table public.transactions add column if not exists paid_at timestamptz;
alter table public.transactions add column if not exists dropped_off_at timestamptz;
alter table public.transactions add column if not exists dropoff_deadline timestamptz;
alter table public.transactions add column if not exists pickup_deadline timestamptz;

create index if not exists idx_tx_status on public.transactions (status);

-- ------------------------------------------------------------
-- Realtime: let buyer & seller see status changes live.
-- (adds the tables to the supabase_realtime publication if not already there)
-- ------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'transactions'
  ) then
    alter publication supabase_realtime add table public.transactions;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notifications'
  ) then
    alter publication supabase_realtime add table public.notifications;
  end if;
end $$;

-- ------------------------------------------------------------
-- Reserve the listing when an order is placed; free it if cancelled.
-- (SECURITY DEFINER so the buyer's insert can flip the seller's listing.)
-- ------------------------------------------------------------
create or replace function public.sync_listing_on_tx()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if TG_OP = 'INSERT' then
    update public.listings set status = 'sold' where id = new.listing_id and status = 'active';
  elsif TG_OP = 'UPDATE' then
    if new.status = 'cancelled' and old.status <> 'cancelled' then
      update public.listings set status = 'active' where id = new.listing_id and status = 'sold';
    end if;
  end if;
  return new;
end $$;

drop trigger if exists trg_tx_sync_listing on public.transactions;
create trigger trg_tx_sync_listing
  after insert or update on public.transactions
  for each row execute function public.sync_listing_on_tx();

-- Let the two parties of a transaction read the listing even after it's marked
-- sold (base listings select is active/own only).
drop policy if exists listings_select_txn_party on public.listings;
create policy listings_select_txn_party on public.listings
  for select using (
    exists (
      select 1 from public.transactions t
      where t.listing_id = listings.id and (t.buyer_id = auth.uid() or t.seller_id = auth.uid())
    )
  );
